### ISSUE TITLE
JPN - ADMIN 2 contains no shapeName 

### ISSUE THREAD

**Issue by maniadel** [wmgeolab/gbRelease#10]
Hello,
I checked your data for Japan and it looks like the  shapeName is missing. 

Metadata details: 

boundaryID JPN-ADM2-2_0_1-G286
boundaryISO JPN
boundaryYear 2017.0
boundaryType ADM2
boundarySource-1 OpenStreetMap
boundarySource-2 Wambacher
boundaryLicense "Open Data Commons Open Database License 1.0"
licenseDetail "Open Data Commons Open Database License 1.0"
licenseSource https://www.openstreetmap.org/copyright
boundarySourceURL https://wambachers-osm.website/boundaries/
boundaryUpdate 2020-01-16
downloadURL https://geoboundaries.org/data/geoBoundaries-2_0_1/JPN/ADM2/geoBoundaries-2_0_1-JPN-ADM2-all.zip

**Comment by DanRunfola** [comment]
Thanks for noting this - we just did a quick look and the column was misnamed in our raw data, so our processing script was omitting the names.  This should be fixed in our next release (3.0, targeting end of May).
![image](https://user-images.githubusercontent.com/7882645/80003645-51747d80-848f-11ea-964d-f46ddc230b76.png)

**Comment by maniadel** [comment]
Thank you for the reactivity.

**Comment by DanRunfola** [comment]
This has been updated / fixed, and is now available in our 3.0 release here:

https://www.geoboundaries.org/downloadFull.html

![image](https://user-images.githubusercontent.com/7882645/83439035-5a525a80-a410-11ea-9426-c9046cd891a3.png)
