### ISSUE TITLE
seeming difference in character encoding between precise and simplified shapefiles

### ISSUE THREAD

**Issue by andysouth** [wmgeolab/gbRelease#138]
Firstly to say that I think that geoboundaries is amazing and it's great to see you putting together such a useful resource so transparently.

I've been accessing boundaries through the rgeoboundaries R package and it seems that the the simplified layers are encoded in UTF8 and the precise ones are not.

Currently rgeoboundaries does not specify UTF8 and thus the accents in the simplified layers are malformed as indicated in wmgeolab/rgeoboundaries#4 and in this prototype app I'm developing https://andysouth.shinyapps.io/afriadmin-compare/. 

I can get them to work by specifying UTF8, but then it doesn't work for the precise ones.

Is the plan for the next release to be all UTF8 or not ? Or am I doing something wrong ?

Thanks,
Andy

**Comment by DanRunfola** [comment]
Well - this looks like a bug!  I'll dig in for our next release.

Also - very cool app.  We are actually right in the middle of developing something similar, but way behind where you are.  Any chance you would open your code eventually so we could contribute?

**Comment by andysouth** [comment]
Thanks Dan !
afrimapr code is being developed in the open, we welcome any input.
The app code is here : https://github.com/afrimapr/afriadmin/tree/master/inst/shiny/afriadmin-compare

**Comment by andysouth** [comment]
Hi @DanRunfola,
FYI we've (with @dickoa) put a patch in regeoboundaries and the app to cope with the different encoding, it seems that it is just the hpscu layers that are not UTF8.
We plan to point people to the app, is there anything that you like us to add/change before we do that ?
Thanks,
Andy

**Comment by DanRunfola** [comment]
Hi Andy,

No, please go ahead and launch!  We'll likely do a few PRs into your repository later with some additions, hopefully adding a few pieces that we had been working on.

In the meantime, the encoding issue will be fixed in gb 4.0.

Also, for your awareness in 4.0 we'll be adding an additional option to the API, which will be license type.  The default will be gbOpen (what we have today), and new ones will include gbHumanitarian (most up to date, fuzziest licenses) and gbAuthoritarian (no global coverage, only from official sources, any license that allows redistribution/modification for standardization of the product).  The rest of the API should still function exactly how it does today, so you shouldn't need to make any changes on your side _unless_ you want to stick with gb3.0 (our current version); in that case you will want to make sure that your VER = 3_0_0 in the API call.

**Comment by andysouth** [comment]
Thanks Dan, sounds great. We've started talking about our app on twitter, feel free to promote in your networks. Look forward to collaborating.

**Comment by DanRunfola** [comment]
Looping back on this - we're moving our entire build routine into github, and the encoding error has now been fixed in prep for the next release.  A .decode("latin") that snuck into the old code was the culprit :) 
https://github.com/wmgeolab/geoBoundaryBot/commit/ad1985158da2ab4082f4549f1523cef1e3a44638
