### ISSUE TITLE
South Africa (ZAF) ADM 0/1/2/3/4 Disagreement

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#23]
South Africa has a disagreement across administrative levels. ADM 1 includes territory not encompassed in other boundary levels. This difference largely appears to be water boundary along the coastline, but there is a major difference as ADM 1 includes Marion Island while the other boundaries do not. Thus, the coastline of ADM 1 should be corrected while the other boundaries need to include Marion Island.

**Comment by nmspage** [comment]
I checked ZAF ADM0-4 and noticed a few things:
1. the metadata sheet and the dataset tracker sheet are inconsistent as to where the data came from. I am assuming it was from OSM Wambacher because that's what the metadata sheet said
2. in addition to the expanded coastline of ADM1, there were also holes in ADM3
3. there were also inconsistencies between ADMs of not just Marion and Prince Edward Island, but also other islands off the coast including Robben Island

To correct these, I:
1. took inventory of islands off the coast and realized ADM0 included them all. So I copied the layer, exploded it, and isolated the islands to merge with all of the other ADMs 
2. exported features of the Prince Edward Islands (including Marion Island) to merge with other ADMs
3. Fixed holes in ADM3 by using ADM4 and selecting wards that were a part of each municipality, exporting those features, merging them, and then merging those new polygons with ADM3 and researching their names. They were excluded because they were a separate type of municipality (metropolitan rather than local)
4. Fixed the coastline of ADM1 by similar methodology of ADM3, where I used ADM2 to select features that were supposed to be in that province, exported those features, merged them, and merged those polygons with ADM1 and edited attributes

All of the islands, boundaries, and attribute tables and projections should be uniform now and corrected. I re-uploaded into open release, but I also kept the old shapefiles on my computer just in case.
