### ISSUE TITLE
NRU ADM 1-2 Holes

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/gbRelease#37]
Both the ADM 1 and 2 layers for Nauru have large center holes. This problem with the data will need to be corrected in the next release with new shapefiles from open GIS repositories or digitized shapefiles from open source map images.

<img width="287" alt="geoBoundariesPreview-3_0_0-NRU-ADM1" src="https://user-images.githubusercontent.com/49990394/83886409-0ea3f780-a715-11ea-86f9-1b82dc00a532.png">

**Comment by sgmurphy00** [comment]
ADM1 resolved by digitization of GNU FDL licensed .png map.

**Comment by nmspage** [comment]
The reason that there is a hole in the center of NRU_ADM2 is because the raw data was taken from a site called POPGIS3, which published the region as an enumeration area, not as an official ADM2 layer. The data for the enumeration area was taken from the 2011 Nauru Population and Housing Census, but the polygons do not seem to accurately represent any regions or communities. It appears that the only administrative boundary devolution is ADM1 - regions, and I cannot find any evidence of an ADM2 existence.

**Comment by DanRunfola** [comment]
Solution in this case: we have updated ADM1 with a new source that is complete (GNU licensed).
We will be removing ADM2 from the release in 3.1, as there is not evidence that Nauru has formal / official ADM2s.  I am going to leave this ticket flagged as an oddity in case someone has knowledge of official Nauru ADM2 boundaries.
