### ISSUE TITLE
Norway missing northern island of Svalbard 

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbRelease#38]
Svalbard is missing from our ADM layers of Norawy.  Aiming to fix this one for 3.1.

**Comment by sgmurphy00** [comment]
Just had a few questions about how to treat this issue in 3.1:

Svalbard is not the only ‘integral territory’ owned by Norway which doesn’t appear in our release- we’re also missing Jan Mayen, a tiny island ~1130km SW of Svalbard. Both are part of the Kingdom of Norway but are not assigned any administrative division, likely due to very low yet densely grouped population (88.7% of Svalbard’s ~2600 inhabitants live in the capital, the rest by and large are coal miners and oil drillers. Jan Mayen has a current permanent population of 18, consisting of military personnel monitoring weather in a single compound). 

Norway also has 3 ‘dependent territories’ in the Southern Hemisphere, namely Bouvetøya, Peter I Island, and Queen Maud Land. All three are uninhabited; the first two are remote subarctic islands, and Queen Maud Land is a section of Antarctic land. I wasn’t planning on including these, and don’t even know if the data exists for them yet, but I could digitize for completion’s sake.

So first off, include Jan Mayen in the release alongside Svalbard?
And, since there is no ADM level formally assigned for either territory, how should they be labeled in the data?

**Comment by DanRunfola** [comment]
At the moment we can't find evidence that these territories are formally a part of any ADMs; ADM1 is likely the best fit, but that would be an arbitrary decision on our part.  Marking this as an oddity in case anyone from the community has knowledge we can't find on the topic; in the interim we will leave these out.
