### ISSUE TITLE
Inconsistency in Egypt / Sudan contested border

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbRelease#39]
Egypt and Sudan share a contested border to the Southeast (Halyib Triangle).  In the individual shapefiles for each country, both countries should claim this space.  However, right now:
EGYPT ADM0 - ADM3 all claim this space.
SDN0 does not claim this space, and should.
SDN1 does not claim this space, and should.
SDN2 does claim this space.

Change needed to close this is to ensure SDN1 and SDN2 both include Sudanese claims in the Halyib Triangle.

**Comment by sgmurphy00** [comment]
Updated SDN0 and SDN1 by using SDN2 as a template for the Halayib Triangle polygon shape. Exact methodology was to:
Split SDN_ADM2 (Red Sea State, which Halayib Triangle region is within), 
Union the Halayib Triangle poly with SDN0 and SDN1
Fill gaps with additional autocompleted poly as needed, then
Union resulting polygons to yield completed adm1 Red Sea State and adm0. 

Checked the metadata on SDN2 after completing the files (did not update in repository yet) to find that SDN2 was sourced from OCHA under a humanitarian only license.  Would this affect the licensure of SDN0 and SDN1, and if so, how should these be treated from a license standpoint?

**Comment by DanRunfola** [comment]
Because of the licensure issue, we'll need to find an alternative approach to the Halayib Triangle.  Working through it.

**Comment by nmspage** [comment]
Downloaded and digitized the Halayib Triangle from a map on wikipedia (CC-SA) to merge with the ADM0 and ADM1 layers of Sudan. I also noticed that there were inconsistencies between ADM0-2 along the southern border regarding the Kafia Kingi Area and the Abyei Area. Both Sudan and South Sudan claim these areas, and after checking SSD_ADM0, it appears that they are not a part of that boundary. I digitized both the Kafia Kingi and Abyei Areas and added them to ADM0 and ADM1 since ADM2 included them. Metadata is updated to include wikipedia. I re-uploaded ADM0 and ADM1 into open release.
